name: Deployer EC2

on:
  workflow_run:
    workflows: ["CI/CD - Outsera API"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deployer-ec2:
    name: Deployer EC2
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deployer EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e
            kubectl set image deployment/outsera-api outsera-api=ghcr.io/edilson-lessadev/outsera-api:${{ github.event.workflow_run.head_sha }}
            kubectl rollout status deployment/outsera-api
            kubectl get pods

            POD=\$(kubectl get pods -l app=outsera-api -o jsonpath='{.items[0].metadata.name}')
            kubectl port-forward pod/\$POD 18081:8081 >/tmp/outsera-port-forward.log 2>&1 &
            PF_PID=\$!

            sleep 20
            curl --retry 10 --retry-delay 3 --retry-connrefused -f http://127.0.0.1:18081/actuator/health

            kill \$PF_PID || true
          EOF