name: CI - Outsera API

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - outseraDesafio
  pull_request:
    branches:
      - outseraDesafio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build e testes
        run: mvn clean verify

      - name: Publicar artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: outsera-api-jar
          path: target/*.jar